# Generated by Django 2.2.1 on 2020-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200506_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryregion',
            name='province_state',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
