# Generated by Django 2.2.1 on 2020-05-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200506_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystatistics',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailystatistics',
            name='country_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CountryRegion'),
        ),
    ]
